[package]
name = "ckb-dynamic-loading-secp256k1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.2"
ckb-lib-secp256k1 = { path = "../../ckb-lib-secp256k1" }
blake2b-ref = "0.1"
